version: '3.7'

services:
  backend:
    build: ../../backend
    ports:
      - "3050:3050"

  minio_for_backend:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z-cpuv1
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      MINIO_ROOT_USER: ${SANDBOX__MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SANDBOX__MINIO_ROOT_PASSWORD}
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_backend_data:/data

volumes:
  minio_backend_data:
