version: '3.7'

services:
  backend:
    build: ../../backend
    ports:
      - "3050:3050"
    environment:
      MINIO_ROOT_USER: ${SANDBOX__MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SANDBOX__MINIO_ROOT_PASSWORD}
      MINIO_HOST: ${SANDBOX_MINIO_HOST}
    volumes:
      - db_data:/backend/db/data
      - web_static:/backend/static:ro
    depends_on:
      minio_for_backend:
        condition: service_healthy
      frontend:
        condition: service_started

  frontend:
    build: ../../frontend
    command: npm run prod:move-assets
    volumes:
      - web_static:/frontend/static:wo

  minio_for_backend:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z-cpuv1
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${SANDBOX__MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SANDBOX__MINIO_ROOT_PASSWORD}
    ports:
      - "10000:9000"
      - "10001:9001"

    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    volumes:
      - minio_backend_data:/data

volumes:
  minio_backend_data:
  db_data:
  web_static:
