version: "3.7"

services:
  backend:
    environment:
      VITE_DEV_HOST: ${VITE_DEV_HOST}

  frontend:
    image: frontend_dev
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/frontend
      - /frontend/node_modules
